addSbtPlugin("com.typesafe.sbt" % "sbt-twirl" % "1.3.13")
addSbtPlugin("com.github.gseitz" % "sbt-release" % "1.0.8")
addSbtPlugin("org.xerial.sbt" % "sbt-sonatype" % "2.3")
addSbtPlugin("com.github.stonexx.sbt" % "sbt-webpack" % "1.3.1")
addSbtPlugin("io.get-coursier" % "sbt-coursier" % "1.0.3")